language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

# command to install dependencies
install:
  # older versions of pip won't work
  - sudo apt-get install libyaml-dev
  - pip install nose
  - pip install -U setuptools pip
  - pip install -r requirements.txt
  - pip --version
  - "VEXT_RELOAD_HACK=1 python setup.py install"
  - vext -s

# command to run tests
script:
  - which nosetests 
  - export VEXT_DEBUG_LOG=1
  - nosetests
