matrix:
  include:
    - os: linux
      sudo: required
      dist: wily
      language: generic
      env: PYTHON="python2" PACKAGES="libpython-dev python-setuptools"
    - os: linux
      sudo: required
      dist: wily
      language: generic
      env: PYTHON="python2" IN_VENV="1" PACKAGES="libpython-dev python-setuptools"
    - os: linux
      sudo: required
      dist: wily
      language: generic
      env: PYTHON="python3" PACKAGES="libpython3-dev python3-setuptools"
    - os: linux
      sudo: required
      dist: wily
      language: generic
      env: PYTHON="python3" IN_VENV="1" PACKAGES="libpython3-dev python3-setuptools"

install:
 - if [ "$IN_VENV" == "1" ]; then virtualenv --python=$PYTHON _venv; PYTHON=_venv/bin/python; fi
 - sudo apt-get update -q
 - echo sudo apt-get install --no-install-recommends $(echo $PACKAGES)
 - sudo apt-get install --no-install-recommends $(echo $PACKAGES)
 - echo PYTHON: $PYTHON $($PYTHON --version)
 - $PYTHON setup.py install

script:
 - $PYTHON ./text.py --in_venv=$(IN_VENV)
