matrix:
  include:
    - os: linux
      sudo: required
      dist: wily
      language: generic
      env: PYTHON="python2" PACKAGES="python-pip python-setuptools"
    - os: linux
      sudo: required
      dist: wily
      language: generic
      env: PYTHON="python2" IN_VENV="1" PACKAGES="python-pip python-setuptools"
    - os: linux
      sudo: required
      dist: wily
      language: generic
      env: PYTHON="python3" PACKAGES="python3-pip python3-setuptools"
    - os: linux
      sudo: required
      dist: wily
      language: generic
      env: PYTHON="python3" IN_VENV="1" PACKAGES="python3-pip python3-setuptools"

install:
 - if [ "$IN_VENV" == "1" ]; then virtualenv --python=$PYTHON _venv; export PYTHON=_venv/bin/python; fi
 - if [ "$IN_VENV" != "1" ]; then export PYTHON="sudo $PYTHON"; fi
 - sudo apt-get update -q
 - sudo apt-get install $(echo $PACKAGES)
 - which $PYTHON
 - $PYTHON --version
 - $PYTHON -mpip show setuptools
 - $PYTHON setup.py install
 - $PYTHON -mpip show setuptools

script:
 - if [ "$IN_VENV" == "1" ]; then export PYTHON=_venv/bin/python; fi
 - if [ "$IN_VENV" != "1" ]; then export PYTHON="sudo $PYTHON"; fi
 - $PYTHON -mpip show setuptools
 - $PYTHON ./tests/tests.py --in-venv=$IN_VENV
