matrix:
  include:
    - os: linux
      sudo: required
      dist: wily
      language: generic
      env: PYTHON="python2" PACKAGES="curl python-setuptools"
    - os: linux
      sudo: required
      dist: wily
      language: generic
      env: PYTHON="python2" IN_VENV="1" PACKAGES="curl python-setuptools"
    - os: linux
      sudo: required
      dist: wily
      language: generic
      env: PYTHON="python3" PACKAGES="curl python3-setuptools"
    - os: linux
      sudo: required
      dist: wily
      language: generic
      env: PYTHON="python3" IN_VENV="1" PACKAGES="curl python3-setuptools"

install:
 - lsb_release -a
 - if [ "$IN_VENV" == "1" ]; then virtualenv --python=$PYTHON _venv; export RUN_PYTHON=_venv/bin/python; fi
 - if [ "$IN_VENV" != "1" ]; then export RUN_PYTHON="sudo $PYTHON"; fi
 - sudo apt-get update -q
 - sudo apt-get install $(echo $PACKAGES)
 - echo $RUN_PYTHON
 - which $RUN_PYTHON
 - $RUN_PYTHON --version
 - $RUN_PYTHON -mpip show setuptools
 - $RUN_PYTHON setup.py install
 - $RUN_PYTHON -mpip show setuptools

script:
 - if [ "$IN_VENV" == "1" ]; then export RUN_PYTHON=_venv/bin/python; fi
 - if [ "$IN_VENV" != "1" ]; then export RUN_PYTHON="sudo $PYTHON"; fi
 - $RUN_PYTHON -mpip show setuptools
 - $RUN_PYTHON ./tests/tests.py --in-venv=$IN_VENV
