matrix:
  include:
    - os: linux
      sudo: required
      dist: wily
      language: generic
      env: PYTHON="sudo python2" PACKAGES="python-setuptools"
    - os: linux
      sudo: required
      dist: wily
      language: generic
      env: PYTHON="python2" IN_VENV="1" PACKAGES="python-setuptools"
    - os: linux
      sudo: required
      dist: wily
      language: generic
      env: PYTHON="sudo python3" PACKAGES="python3-setuptools"
    - os: linux
      sudo: required
      dist: wily
      language: generic
      env: PYTHON="python3" IN_VENV="1" PACKAGES="python3-setuptools"

install:
 - if [ "$IN_VENV" == "1" ]; then virtualenv --python=$PYTHON _venv; export PYTHON=_venv/bin/python; fi
 - sudo apt-get update -q
 - sudo apt-get install $(echo $PACKAGES)
 - which $PYTHON; python --version
 - pwd; ls
 - $PYTHON setup.py install

script:
 - $PYTHON ./tests/text.py --in_venv=$IN_VENV
